[package]
name = "shipcheck-cli"
description = "Command line interface for Shipcheck"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "shipcheck"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde_json = "1"
shipcheck-core = { path = "../shipcheck-core" }
shipcheck-engine = { path = "../shipcheck-engine" }

[lints]
workspace = true
